# Generated by Django 5.1 on 2024-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('terminado', 'tarea finalizada'), ('incompleto', 'tareas incompleta')], default='incompleto', max_length=100),
        ),
    ]
